[TIME]: 0:01:03.929363
Randoop for Java version "4.3.2, local changes, branch master, commit df17bc8, 2023-01-08".
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Cannot instantiate non-accessible class org.joo.promise4j.impl.InternalJoinedResults specified via --testclass or --classlist.

Will try to generate tests for 30 out of 31 classes.
PUBLIC MEMBERS=155
Explorer = ForwardGenerator(steps: 0, null steps: 0, num_sequences_generated: 0;
    allSequences: 0, regresson seqs: 0, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 0;
    sideEffectFreeMethods: 1115, runtimePrimitivesSeen: 38)

Progress update: steps=1, test inputs generated=0, failing inputs=0      (2023-11-20T08:45:28.021Z     58.6M used)02:45:39.721 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:39.769 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:39.770 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:44.931 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:50.102 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:50.179 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:50.203 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling fail
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:71) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.fail(SimpleFailurePromise.java:29) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:50.221 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:50.222 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:50.222 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:55.500 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:55.615 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:55.615 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:55.615 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:55.775 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:55.900 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:45:55.901 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.112 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.228 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling fail
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:71) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.fail(SimpleFailurePromise.java:29) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.236 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.245 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.245 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.332 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.332 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.409 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.493 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.always(SimpleDonePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.500 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.501 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.552 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.552 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.577 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.590 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.629 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.732 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.733 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.734 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.797 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.822 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.841 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.868 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.869 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:01.881 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.AsyncDeferredObject.always(AsyncDeferredObject.java:90) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.227 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.always(SimpleDonePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.263 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.303 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.405 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.405 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.452 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.549 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.586 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.610 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.610 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.671 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.717 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:02.979 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:03.016 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:03.366 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.done(SimpleDonePromise.java:24) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:03.473 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:03.473 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.082 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.367 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.368 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.423 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.597 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.597 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.615 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.626 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.636 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.759 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.759 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.759 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.760 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.760 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.841 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.882 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.AsyncDeferredObject.always(AsyncDeferredObject.java:90) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]

Progress update: steps=1000, test inputs generated=328, failing inputs=0      (2023-11-20T08:46:04.925Z     386M used)02:46:04.949 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:04.975 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:05.116 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:05.116 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:05.117 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:05.161 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.done(SimpleDonePromise.java:24) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:05.180 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:05.181 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:05.226 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:05.607 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:06.045 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:06.045 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:11.175 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.done(SimpleDonePromise.java:24) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.201 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.226 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.246 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.307 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.373 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling fail
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:71) [classes/:?]
	at org.joo.promise4j.impl.AsyncDeferredObject.fail(AsyncDeferredObject.java:106) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.404 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.431 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.568 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.always(SimpleDonePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:16.582 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:21.730 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:21.732 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:21.765 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:21.891 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:26.918 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:26.930 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:26.930 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:26.931 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.212 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling fail
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:71) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.fail(SimpleFailurePromise.java:29) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.222 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.424 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.425 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.472 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.622 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.742 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.always(SimpleDonePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.856 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
02:46:27.857 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]

Progress update: steps=1158, test inputs generated=433, failing inputs=0      (2023-11-20T08:46:28.035Z     143M used)
Progress update: steps=1158, test inputs generated=434, failing inputs=0      (2023-11-20T08:46:28.209Z     203M used)
Normal method executions: 145755
Exceptional method executions: 133

Average method execution time (normal termination):      0.0346
Average method execution time (exceptional termination): 0.286
Approximate memory usage 203M
Explorer = ForwardGenerator(steps: 1158, null steps: 724, num_sequences_generated: 434;
    allSequences: 434, regresson seqs: 423, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 11;
    sideEffectFreeMethods: 1115, runtimePrimitivesSeen: 42)

No error-revealing tests to output.

About to look for failing assertions in 263 regression sequences.

Regression test output:
Regression test count: 263
Writing regression JUnit tests...
Created file /Users/yhcrown/Documents/GitHub/generated-flaky-study/randoop_tests/dungba88-promise4j/68a8814ae6d5115bb060c839fd7bdaa02c58dd08/alltests/TestGroup100Case0.java
Created file /Users/yhcrown/Documents/GitHub/generated-flaky-study/randoop_tests/dungba88-promise4j/68a8814ae6d5115bb060c839fd7bdaa02c58dd08/alltests/TestGroup100Case.java
Wrote regression JUnit tests.
About to look for flaky methods.

Invalid tests generated: 0
