[TIME]: 0:01:03.652274
Randoop for Java version "4.3.2, local changes, branch master, commit df17bc8, 2023-01-08".
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Cannot instantiate non-accessible class org.joo.promise4j.impl.InternalJoinedResults specified via --testclass or --classlist.

Will try to generate tests for 30 out of 31 classes.
PUBLIC MEMBERS=155
Explorer = ForwardGenerator(steps: 0, null steps: 0, num_sequences_generated: 0;
    allSequences: 0, regresson seqs: 0, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 0;
    sideEffectFreeMethods: 1115, runtimePrimitivesSeen: 38)

Progress update: steps=1, test inputs generated=0, failing inputs=0      (2023-10-31T23:36:33.659Z     57.2M used)18:36:45.394 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:45.435 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:45.435 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:50.614 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:55.794 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:55.883 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:55.908 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling fail
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:71) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.fail(SimpleFailurePromise.java:29) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:55.921 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:55.921 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:36:55.921 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:01.198 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:01.318 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:01.318 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:01.319 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:01.452 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:01.587 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:01.588 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:06.806 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:06.928 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling fail
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:71) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.fail(SimpleFailurePromise.java:29) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:06.936 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:06.943 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:06.944 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.031 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.031 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.104 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.185 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.always(SimpleDonePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.192 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.193 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.249 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.250 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.275 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.283 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.331 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.439 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.440 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.441 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.507 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.531 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.548 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.576 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.580 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.590 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.AsyncDeferredObject.always(AsyncDeferredObject.java:90) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.927 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.always(SimpleDonePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:07.972 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.014 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.114 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.114 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.161 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.278 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.308 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.337 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.337 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.394 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.437 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.704 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:08.746 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:09.107 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.done(SimpleDonePromise.java:24) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:09.210 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:09.211 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:09.821 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.118 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.118 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.174 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.347 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.347 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.363 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.375 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.386 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.510 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.510 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.510 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.512 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.513 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.600 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.644 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.AsyncDeferredObject.always(AsyncDeferredObject.java:90) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]

Progress update: steps=1000, test inputs generated=328, failing inputs=0      (2023-10-31T23:37:10.696Z     463M used)18:37:10.752 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.781 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.923 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.924 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.924 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.964 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.done(SimpleDonePromise.java:24) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.984 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:10.984 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:11.028 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:11.438 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.always(CompletableDeferredObject.java:46) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:11.915 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:11.915 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:17.063 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.done(SimpleDonePromise.java:24) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.099 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.134 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.155 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.215 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.282 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling fail
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:71) [classes/:?]
	at org.joo.promise4j.impl.AsyncDeferredObject.fail(AsyncDeferredObject.java:106) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.314 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.342 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.486 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleDonePromise.always(SimpleDonePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:22.503 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:27.651 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:27.653 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:27.699 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:27.834 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.always(SimpleFailurePromise.java:35) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:32.870 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:32.893 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:32.893 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:32.893 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling always
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:82) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$always$2(CompletableDeferredObject.java:46) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.reject(CompletableDeferredObject.java:58) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:33.168 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling fail
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:71) [classes/:?]
	at org.joo.promise4j.impl.SimpleFailurePromise.fail(SimpleFailurePromise.java:29) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:33.179 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.resolve(CompletableDeferredObject.java:52) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:33.387 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:33.387 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:33.435 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]
18:37:33.582 [randoop.util.RunnerThread] ERROR org.joo.promise4j.impl.AbstractPromise - Exception caught while handling done
java.lang.NullPointerException: null
	at org.joo.promise4j.impl.AbstractPromise.complete(AbstractPromise.java:61) ~[classes/:?]
	at org.joo.promise4j.impl.CompletableDeferredObject.lambda$done$0(CompletableDeferredObject.java:34) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) [?:1.8.0_382]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) [?:1.8.0_382]
	at org.joo.promise4j.impl.CompletableDeferredObject.done(CompletableDeferredObject.java:34) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at randoop.util.MethodReflectionCode.runReflectionCodeRaw(MethodReflectionCode.java:53) [randoop-all-4.3.2.jar:?]
	at randoop.util.ReflectionCode.runReflectionCode(ReflectionCode.java:63) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.executeReflectionCode(RunnerThread.java:49) [randoop-all-4.3.2.jar:?]
	at randoop.util.RunnerThread.run(RunnerThread.java:43) [randoop-all-4.3.2.jar:?]

Progress update: steps=1148, test inputs generated=426, failing inputs=0      (2023-10-31T23:37:33.660Z     273M used)
Normal method executions: 133346
Exceptional method executions: 129

Average method execution time (normal termination):      0.0363
Average method execution time (exceptional termination): 0.217
Approximate memory usage 273M
Explorer = ForwardGenerator(steps: 1148, null steps: 722, num_sequences_generated: 426;
    allSequences: 426, regresson seqs: 415, error seqs: 0=0=0, invalid seqs: 0, subsumed_sequences: 0, num_failed_output_test: 11;
    sideEffectFreeMethods: 1115, runtimePrimitivesSeen: 42)

No error-revealing tests to output.

About to look for failing assertions in 260 regression sequences.

Regression test output:
Regression test count: 260
Writing regression JUnit tests...

                                                                                                                                                                                                       
Created file /Users/yhcrown/Documents/GitHub/generated-flaky-study/randoop_tests/dungba88-promise4j/68a8814ae6d5115bb060c839fd7bdaa02c58dd08/alltests/TestGroup100Case0.java
Created file /Users/yhcrown/Documents/GitHub/generated-flaky-study/randoop_tests/dungba88-promise4j/68a8814ae6d5115bb060c839fd7bdaa02c58dd08/alltests/TestGroup100Case.java
Wrote regression JUnit tests.
About to look for flaky methods.

Invalid tests generated: 0
